In [1]:
# Added to github on 9/5

In [2]:
# Shortcomings/Assumptions: higher values realistically would not have the same permutation distribution as middle ones, 
# i.e. it would take dramatic changes realistically esp. politically to move from a 9 to a 10. Would be like California changing from 
# 50% to 60% renewable

In [3]:
for i in np.nditer(smpat):
    print i
    
# LEARNED: don't forget double (()) 's for numpy operations and stacking

NameError: name 'np' is not defined

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import numpy.matlib as M
from numpy.matlib import rand,zeros,ones,empty,eye


/home/spencer/Apps/anaconda2/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')


In [ ]:
# as array = matrix.A

In [8]:
# Create a Sample Matrix 10 x 10 from mu + std*randn
5+M.randn((10,10))*1


matrix([[ 7.54655784,  4.54809612,  3.79772067,  4.47507438,  5.02288419,
          5.90900723,  5.45275181,  4.5450498 ,  5.02041455,  3.22430794],
        [ 3.71433804,  4.76216968,  5.55653053,  4.35158229,  4.21558609,
          6.58454706,  6.80198164,  5.38964217,  5.15278264,  3.97776978],
        [ 5.41176448,  4.95109407,  5.17902588,  4.87382761,  3.0793082 ,
          4.43380008,  5.68891412,  5.37265852,  5.59201007,  5.47279851],
        [ 5.92023292,  5.10166088,  6.74347523,  4.38472996,  6.20355103,
          4.94178648,  4.38125384,  2.91440779,  5.76567083,  4.20174503],
        [ 3.61091049,  5.61538684,  2.63543173,  4.64542912,  4.34268658,
          5.20734746,  4.81361461,  5.2223076 ,  5.6278885 ,  6.08936685],
        [ 5.88143037,  5.0365629 ,  4.64729696,  4.17091958,  4.34154398,
          3.08548285,  2.88015479,  4.02264214,  4.13589707,  3.9745363 ],
        [ 5.31229534,  4.35244052,  5.20197319,  6.20995376,  4.29987505,
          4.19703448,  3.4110315

In [9]:
# One Loop

# Print Loop number n

# How are we permuting the matrix?
# uniform, normally, etc

# Save the matrix for inspection

# Calculate Rankings and Save
# save as ?? 


In [9]:
# Create Column Array of Ones
onemat = ones((10)).A.T
# Create Array with Columns as 1s, 2s, 3s, etc
smpat = np.hstack((onemat, 2*onemat, 3*onemat, 4*onemat, 5*onemat, 6*onemat, 7*onemat, 8*onemat, 9*onemat, 10*onemat))
# Initialize results matrix
results = zeros((10,10)).A

In [19]:
%time
results = np.copy(smpat)
N = 100
# N randomizations (of master ranking), creating 10x10xN matrix
# get results of kth simulation with results[:,:,k-1]
# (Random Normal Permutation)
for i in range(1,N):
    cpy = np.copy(smpat)
    # Permute
    # If < 0 set to 0, if > 10 set to 10
    for x in np.nditer(cpy, op_flags=['readwrite']):
        # random samples = mu + sigma * randn
        x[...] = x + M.randn(1,1)*2
        if x>10: x[...] = 10
        if x<0: x[...] = 0
    results = np.dstack((results,cpy))


CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 4.05 µs


In [20]:
results.shape

(10, 10, 100)

In [32]:
results[:,:,0] # Gives Resulting Matrix ()


array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.]])

In [ ]:
# TODO: if each site is a ROW, average across the rows for the final value


In [33]:
results[:,:,0].mean()

5.5

In [35]:
# Apply along axis=1 i.e. columns
np.apply_along_axis(lambda x: x.mean(), 1, results[:,:,0])
# now we have array of length = 10 with averages for each row

array([ 5.5,  5.5,  5.5,  5.5,  5.5,  5.5,  5.5,  5.5,  5.5,  5.5])

In [39]:
# But if we want to just look at one site/row:
# array of averages for row 1
site1 = results[0,:,:]
np.apply_along_axis(lambda x: x.mean(), 1, site1)

array([ 1.13329094,  2.55189085,  2.65432935,  4.05155546,  4.88690972,
        5.89680002,  7.07206782,  8.04852019,  8.67522853,  9.37974262])